# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/huashan/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/huashan

PRODUCT_COPY_FILES += \
    vendor/sony/huashan/proprietary/bin/ta_param_loader:$(TARGET_COPY_OUT_SYSTEM)/bin/ta_param_loader \
    vendor/sony/huashan/proprietary/bin/ta_qmi_service:$(TARGET_COPY_OUT_SYSTEM)/bin/ta_qmi_service \
    vendor/sony/huashan/proprietary/bin/updatemiscta:$(TARGET_COPY_OUT_SYSTEM)/bin/updatemiscta \
    vendor/sony/huashan/proprietary/etc/firmware/cyttsp4_fw.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cyttsp4_fw.bin \
    vendor/sony/huashan/proprietary/etc/firmware/cyttsp_8064_mtp.hex:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cyttsp_8064_mtp.hex \
    vendor/sony/huashan/proprietary/etc/firmware/cyttsp_8960_cdp.hex:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cyttsp_8960_cdp.hex \
    vendor/sony/huashan/proprietary/etc/firmware/dsps.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/dsps.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/dsps.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/dsps.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/dsps.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b04 \
    vendor/sony/huashan/proprietary/etc/firmware/dsps.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b05 \
    vendor/sony/huashan/proprietary/etc/firmware/dsps.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.mdt \
    vendor/sony/huashan/proprietary/etc/firmware/dxhdcp2.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/dxhdcp2.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/dxhdcp2.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/dxhdcp2.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/dxhdcp2.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.mdt \
    vendor/sony/huashan/proprietary/etc/firmware/q6.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/q6.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/q6.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/q6.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b04 \
    vendor/sony/huashan/proprietary/etc/firmware/q6.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b05 \
    vendor/sony/huashan/proprietary/etc/firmware/q6.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b06 \
    vendor/sony/huashan/proprietary/etc/firmware/q6.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.mdt \
    vendor/sony/huashan/proprietary/etc/firmware/tzlibasb.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/tzlibasb.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/tzlibasb.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/tzlibasb.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/tzlibasb.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.mdt \
    vendor/sony/huashan/proprietary/etc/firmware/tzs1sl.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/tzs1sl.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/tzs1sl.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/tzs1sl.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/tzs1sl.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.mdt \
    vendor/sony/huashan/proprietary/etc/firmware/tzsuntory.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/tzsuntory.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/tzsuntory.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/tzsuntory.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/tzsuntory.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.mdt \
    vendor/sony/huashan/proprietary/etc/flashled_calc_parameters.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/flashled_calc_parameters.cfg \
    vendor/sony/huashan/proprietary/lib/hw/camera.vendor.qcom.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.vendor.qcom.so \
    vendor/sony/huashan/proprietary/lib/hw/nfc.msm8960.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/nfc.msm8960.so \
    vendor/sony/huashan/proprietary/lib/libals.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libals.so \
    vendor/sony/huashan/proprietary/lib/libaudcal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudcal.so \
    vendor/sony/huashan/proprietary/lib/libcald_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_client.so \
    vendor/sony/huashan/proprietary/lib/libcald_hal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_hal.so \
    vendor/sony/huashan/proprietary/lib/libcald_imageutil.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_imageutil.so \
    vendor/sony/huashan/proprietary/lib/libcald_pal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_pal.so \
    vendor/sony/huashan/proprietary/lib/libcald_server.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_server.so \
    vendor/sony/huashan/proprietary/lib/libcald_util.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_util.so \
    vendor/sony/huashan/proprietary/lib/libcamera_clientsemc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamera_clientsemc.so \
    vendor/sony/huashan/proprietary/lib/libcameralight.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcameralight.so \
    vendor/sony/huashan/proprietary/lib/libface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libface.so \
    vendor/sony/huashan/proprietary/lib/libmiscta.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmiscta.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_3a_legacy.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_3a_legacy.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_faceproc.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_frameproc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_frameproc.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_plugin.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_statsproc31.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_statsproc31.so \
    vendor/sony/huashan/proprietary/lib/liboemcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/liboemcamera.so \
    vendor/sony/huashan/proprietary/lib/libsys-utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsys-utils.so \
    vendor/sony/huashan/proprietary/vendor/camera/APT00YP1.dat:$(TARGET_COPY_OUT_VENDOR)/camera/APT00YP1.dat \
    vendor/sony/huashan/proprietary/vendor/camera/SMC08BS2.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SMC08BS2.dat \
    vendor/sony/huashan/proprietary/vendor/camera/SMC08BS2_IMX134.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SMC08BS2_IMX134.dat \
    vendor/sony/huashan/proprietary/vendor/camera/SOI08BS2.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2.dat \
    vendor/sony/huashan/proprietary/vendor/camera/SOI08BS2_BU64291.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2_BU64291.dat \
    vendor/sony/huashan/proprietary/vendor/camera/SOI08BS2_IMX134.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2_IMX134.dat \
    vendor/sony/huashan/proprietary/vendor/camera/SOI08BS3.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS3.dat \
    vendor/sony/huashan/proprietary/vendor/camera/SOI08BS3_IMX134.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS3_IMX134.dat \
    vendor/sony/huashan/proprietary/vendor/camera/STW00YP1.dat:$(TARGET_COPY_OUT_VENDOR)/camera/STW00YP1.dat \
    vendor/sony/huashan/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/huashan/proprietary/vendor/camera/product.dat:$(TARGET_COPY_OUT_VENDOR)/camera/product.dat

PRODUCT_PACKAGES += \
    libsensors_akm8963 \
    libta

PRODUCT_COPY_FILES += \
    vendor/sony/huashan/proprietary/bin/efsks:$(TARGET_COPY_OUT_SYSTEM)/bin/efsks \
    vendor/sony/huashan/proprietary/bin/fm_qsoc_patches:$(TARGET_COPY_OUT_SYSTEM)/bin/fm_qsoc_patches \
    vendor/sony/huashan/proprietary/bin/hci_qcomm_init:$(TARGET_COPY_OUT_SYSTEM)/bin/hci_qcomm_init \
    vendor/sony/huashan/proprietary/bin/irsc_util:$(TARGET_COPY_OUT_SYSTEM)/bin/irsc_util \
    vendor/sony/huashan/proprietary/bin/ks:$(TARGET_COPY_OUT_SYSTEM)/bin/ks \
    vendor/sony/huashan/proprietary/bin/netmgrd:$(TARGET_COPY_OUT_SYSTEM)/bin/netmgrd \
    vendor/sony/huashan/proprietary/bin/qcks:$(TARGET_COPY_OUT_SYSTEM)/bin/qcks \
    vendor/sony/huashan/proprietary/bin/qmuxd:$(TARGET_COPY_OUT_SYSTEM)/bin/qmuxd \
    vendor/sony/huashan/proprietary/bin/rmt_storage:$(TARGET_COPY_OUT_SYSTEM)/bin/rmt_storage \
    vendor/sony/huashan/proprietary/bin/secchand:$(TARGET_COPY_OUT_SYSTEM)/bin/secchand \
    vendor/sony/huashan/proprietary/bin/usbhub:$(TARGET_COPY_OUT_SYSTEM)/bin/usbhub \
    vendor/sony/huashan/proprietary/bin/usbhub_init:$(TARGET_COPY_OUT_SYSTEM)/bin/usbhub_init \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b04 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b05 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b06 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b07:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b07 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b08:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b08 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b09:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b09 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.b10:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b10 \
    vendor/sony/huashan/proprietary/etc/firmware/modem.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.mdt \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b04 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b05 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b09:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b09 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b10:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b10 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b11:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b11 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b12:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b12 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b13:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b13 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b15:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b15 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b16:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b16 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b23:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b23 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b24:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b24 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b25:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b25 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b27:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b27 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b28:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b28 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.b31:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b31 \
    vendor/sony/huashan/proprietary/etc/firmware/modem_fw.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.mdt \
    vendor/sony/huashan/proprietary/etc/firmware/vidc.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/vidc.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/vidc.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/vidc.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.b03 \
    vendor/sony/huashan/proprietary/etc/firmware/vidc.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.mdt \
    vendor/sony/huashan/proprietary/etc/firmware/vidc_1080p.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc_1080p.fw \
    vendor/sony/huashan/proprietary/etc/firmware/vidcfw.elf:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidcfw.elf \
    vendor/sony/huashan/proprietary/etc/firmware/wcnss.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b00 \
    vendor/sony/huashan/proprietary/etc/firmware/wcnss.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b01 \
    vendor/sony/huashan/proprietary/etc/firmware/wcnss.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b02 \
    vendor/sony/huashan/proprietary/etc/firmware/wcnss.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b04 \
    vendor/sony/huashan/proprietary/etc/firmware/wcnss.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b05 \
    vendor/sony/huashan/proprietary/etc/firmware/wcnss.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.mdt \
    vendor/sony/huashan/proprietary/lib/hw/gps.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.default.so \
    vendor/sony/huashan/proprietary/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libQSEEComAPI.so \
    vendor/sony/huashan/proprietary/lib/lib_asb_tee.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_asb_tee.so \
    vendor/sony/huashan/proprietary/lib/libacdbloader.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libacdbloader.so \
    vendor/sony/huashan/proprietary/lib/libadsprpc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libadsprpc.so \
    vendor/sony/huashan/proprietary/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdsi_netctrl.so \
    vendor/sony/huashan/proprietary/lib/libdsutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdsutils.so \
    vendor/sony/huashan/proprietary/lib/libgemini.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgemini.so \
    vendor/sony/huashan/proprietary/lib/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgps.utils.so \
    vendor/sony/huashan/proprietary/lib/libidd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libidd.so \
    vendor/sony/huashan/proprietary/lib/libidl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libidl.so \
    vendor/sony/huashan/proprietary/lib/libkeyctrl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libkeyctrl.so \
    vendor/sony/huashan/proprietary/lib/libloc_api_v02.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_api_v02.so \
    vendor/sony/huashan/proprietary/lib/libloc_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_core.so \
    vendor/sony/huashan/proprietary/lib/libloc_ds_api.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_ds_api.so \
    vendor/sony/huashan/proprietary/lib/libloc_eng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_eng.so \
    vendor/sony/huashan/proprietary/lib/libmercury.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmercury.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_hdr_lib.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_image_stab.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_image_stab.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_tintless_algo.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_tintless_wrapper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_tintless_wrapper.so \
    vendor/sony/huashan/proprietary/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_wavelet_lib.so \
    vendor/sony/huashan/proprietary/lib/libmmjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmjpeg.so \
    vendor/sony/huashan/proprietary/lib/libnetmgr.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnetmgr.so \
    vendor/sony/huashan/proprietary/lib/libpin-cache.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libpin-cache.so \
    vendor/sony/huashan/proprietary/lib/libprotobuf-c.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libprotobuf-c.so \
    vendor/sony/huashan/proprietary/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqcci_legacy.so \
    vendor/sony/huashan/proprietary/lib/libqdi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqdi.so \
    vendor/sony/huashan/proprietary/lib/libqdp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqdp.so \
    vendor/sony/huashan/proprietary/lib/libqmi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi.so \
    vendor/sony/huashan/proprietary/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi_client_qmux.so \
    vendor/sony/huashan/proprietary/lib/libqmiservices.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmiservices.so \
    vendor/sony/huashan/proprietary/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libril-qc-qmi-1.so \
    vendor/sony/huashan/proprietary/lib/libs1sl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libs1sl.so \
    vendor/sony/huashan/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/sony/huashan/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    vendor/sony/huashan/proprietary/vendor/lib/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglsubAndroid.so \
    vendor/sony/huashan/proprietary/vendor/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so \
    vendor/sony/huashan/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so \
    vendor/sony/huashan/proprietary/vendor/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so \
    vendor/sony/huashan/proprietary/vendor/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so \
    vendor/sony/huashan/proprietary/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
    vendor/sony/huashan/proprietary/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    vendor/sony/huashan/proprietary/vendor/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so \
    vendor/sony/huashan/proprietary/vendor/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so \
    vendor/sony/huashan/proprietary/vendor/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so \
    vendor/sony/huashan/proprietary/vendor/lib/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a3xx.so \
    vendor/sony/huashan/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/sony/huashan/proprietary/vendor/lib/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgeofence.so \
    vendor/sony/huashan/proprietary/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
    vendor/sony/huashan/proprietary/vendor/lib/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libizat_core.so \
    vendor/sony/huashan/proprietary/vendor/lib/liblbs_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblbs_core.so \
    vendor/sony/huashan/proprietary/vendor/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so \
    vendor/sony/huashan/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/sony/huashan/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/sony/huashan/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/sony/huashan/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/sony/huashan/proprietary/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so \
    vendor/sony/huashan/proprietary/vendor/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so \
    vendor/sony/huashan/proprietary/vendor/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so \
    vendor/sony/huashan/proprietary/vendor/lib/libsc-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a3xx.so \
    vendor/sony/huashan/proprietary/vendor/lib/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstlport.so \
    vendor/sony/huashan/proprietary/vendor/lib/libuiblur.so:$(TARGET_COPY_OUT_VENDOR)/lib/libuiblur.so \
    vendor/sony/huashan/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so

PRODUCT_PACKAGES += \
    libtime_genoff
